### PR TITLE
Modify count() IDL default param

### PR DESCRIPTION
**Pull request by domfarolino**
As suggested in #88

### CODE REVIEW

**Comment by robertkowalski** [comment]
> same for count btw

but depends on implementors buy-in, maybe with the follow up issues easier to solve, things get easily lost over time

**Comment by domfarolino** [comment]
> same for count btw

Sorry I'm a little confused, since this is modifying the `count` IDL. Do you think we should hold off on merging, or at least open some issues before we merge?

**Comment by JosephPecoraro** [comment]
I still think having a `console.count` for a unique place in code is a useful concept, and it would be most natural as the no-argument version. However, I don't seem to have convinced anyone of my position though, heh.

**Comment by robertkowalski** [comment]
> Sorry I'm a little confused, since this is modifying the count IDL. Do you think we should hold off on merging, or at least open some issues before we merge?

ah no sorry, i was just tired and messed things up 

+1 merge it

**Comment by domfarolino** [comment]
@JosephPecoraro Personally I like `= "default"` a bit better, but I'm curious what would the label look like for a call to `count()` that would update a counter unique to the callsite (source:line:column)? Something more friendly than `source:line:column : countNumHere`?

**Pull request merged**
