### PR TITLE
Meta: use the common deploy.sh (with POST_BUILD_STEP)

### PR DESCRIPTION
**Pull request by foolip**
Part of https://github.com/whatwg/meta/issues/11.

### CODE REVIEW

**Comment by domenic** [comment]
A few issues:

- Why doesn't EXTRA_FILES work here?
- Should we add a deploy to the makefile?
- The readme references deploy.sh and so needs an update.

**Comment by foolip** [comment]
> Why doesn't EXTRA_FILES work here?

It's because of the images/ subdirectory. Turns out that `rsync --relative images/*.* deploy/` will create deploy/images/*.*, so I've tweaked this a bit. I could make EXTRA_FILES support this directly, if you think it'll be obvious enough that `EXTRA_FILES="images/*.*"` will create the directory?

> Should we add a deploy to the makefile?

> The readme references deploy.sh and so needs an update.

The POST_BUILD_STEP var needs to be moved to Makefile, but I've made it so, push changes momentarily.

**Comment by foolip** [comment]
This PR now depends on https://github.com/whatwg/whatwg.org/pull/88, branch build will probably fail or be broken.

**Comment by foolip** [comment]
Restarting both builds to see if the world is broken.

**Comment by foolip** [comment]
It worked!

**Pull request merged**
