### PR TITLE
 chore: replace babel-preset-es2015 with babel-preset-env 

### PR DESCRIPTION
**Pull request by hiroppy**
And update README.

### CODE REVIEW

**Comment by hiroppy** [comment]
Thank you for review:)

**Comment by domfarolino** [comment]
I'm not really sure how effective it will be to update the reference implementation here. I know it doesn't get too much TLC these days; I'm not opposed to getting back on top of it, but it also doesn't seem terribly necessary. I think once you're verified (cc @annevk ) and we have a decision on that, we can move forward with this or request some changes. Thanks!

**Comment by annevk** [comment]
Verified!

**Comment by hiroppy** [comment]
@annevk Thanks!

**Comment by domenic** [comment]
I think removing the reference implementation would be a good idea, personally, given how it hasn't kept pace and how the tests should be redundant with web-platform-tests these days.

**Pull request merged**
